version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest test_github_api.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

