version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.12
    steps:
      - checkout
      - run:
          name: Change to project directory
          command: cd GitHubAPI567-HW4a
      - run:
          name: Install dependencies
          command: pip install -r GitHubAPI567-HW4a/requirements.txt
      - run:
          name: Run tests
          command: pytest GitHubAPI567-HW4a/test_github_api.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

