version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install dependencies
          command: pip install -r GitHubAPI567-HW4a/requirements.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

