version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install requests
      - run:
          name: Navigate to subfolder
          command: cd GitHubAPI567-HW4a
      - run:
          name: Run tests
          command: python -m unittest test_github_api.py
workflows:
  version: 2
  build-and-test:
    jobs:
      - build

